# Generated by Django 5.2.7 on 2025-10-18 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0006_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
