# Generated by Django 5.2.7 on 2025-11-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['trip', 'arrival_date', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(help_text='Example categories: sightseeing, food, nightlife, travel, etc.', max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost in USD.', max_digits=8, null=True)),
                ('description', models.TextField(blank=True)),
                ('destination', models.ForeignKey(help_text='The destination where this activity takes place.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='project.destination')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['date', 'time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('packed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(help_text='The trip this item is being packed for.', on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='project.trip')),
            ],
            options={
                'verbose_name': 'Packing Item',
                'verbose_name_plural': 'Packing Items',
                'ordering': ['trip', 'packed', 'item_name'],
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='trip',
            field=models.ForeignKey(help_text='The trip that this destination belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='project.trip'),
        ),
    ]
